name = "VectorAutoregressions"
uuid = "dd6ac5f8-b674-4e69-bae0-bc0b5927a904"
authors = ["Luca Brugnolini and contributors"]
version = "0.1.0"

[deps]
GrowableArrays = "7ebbc34c-24a4-5a3f-b49a-24be4b3feaef"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GrowableArrays = "0.1"
julia = "1"
